languageCode = "en-us"
title = "Proven Systems"
theme = "dimension"
canonifyURLs = true
baseURL = "http://proven.systems/"

[params]
  title = "Proven"
  description = 'Smart contracts for independently verifying the origin of digital documents'
  logo = "fa-diamond"
  copyright = "1AmOXsGnfXdbNg3RMTyPCHkn2aT"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/proven_sys"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/systems.proven"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/proven_sys"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/proven-systems"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/proven"
